date
export dir=$1
echo "Linking mobtimer-api $dir"
rm -rf $dir/src/mobtimer-api
ln -s $PWD/mobtimer-api/src $dir/src/mobtimer-api
Date > $dir/src/Date-autogenerated.txt # todo: Get this line to work on GitPod (Date-autogenerated.txt)